spring.application.name=game-catalog-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.fail-fast=false
