create table users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email),
    constraint ck_users_role check (role in ('PLAYER', 'DEVELOPER', 'ADMIN'))
);
