create table reactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    game_id bigint not null,
    type varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_reactions_user_game unique (user_id, game_id),
    constraint ck_reactions_type check (type in ('LIKE', 'DISLIKE'))
);

create index idx_reactions_game_id on reactions (game_id);

create table library_entries (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    game_id bigint not null,
    added_at timestamp(6) with time zone not null,
    constraint uk_library_entries_user_game unique (user_id, game_id)
);

create table comments (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    game_id bigint not null,
    body varchar(2000) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create index idx_comments_game_id on comments (game_id);
