create table games (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(1000),
    genre varchar(255) not null,
    playable_url varchar(255) not null,
    creator_id bigint not null,
    approval_status varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint ck_games_approval_status check (approval_status in ('PENDING', 'APPROVED', 'REJECTED'))
);

create index idx_games_approval_status on games (approval_status);
create index idx_games_creator_id on games (creator_id);
